version: '3'
services:
  pycram:
    image: intel4coro/artnie-2drpwr-2dassignments-a6f480:24885d1d20a2dc7df20203b27e4770ee22c29095
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    ports: 
      - 8888:8888
    privileged: true
    volumes:
      - ../:/home/jovyan/work

    # for windows and mac, use 'network_mode: bridge'
    # network_mode: host
    # environment:
    #   - ROS_IP=localhost  # change localhost to your wifi IP
    #   - ROS_MASTER_URI=http://localhost:11311  # change 'localhost' to TURTLE IP

